pub const Instruction = enum { ADC, AND, ASL, BCC, BCS, BEQ, BIT, BMI, BNE, BPL, BRA, BRK, BRL, BVC, BVS, CLC, CLD, CLI, CLV, CMP, COP, CPX, CPY, DEC, DEX, DEY, EOR, INC, INX, INY, JMP, JSL, JSR, LDA, LDX, LDY, LSR, MVN, MVP, NOP, ORA, PEA, PEI, PER, PHA, PHB, PHD, PHK, PHP, PHX, PHY, PLA, PLB, PLD, PLP, PLX, PLY, REP, ROL, ROR, RTI, RTL, RTS, SBC, SEC, SED, SEI, SEP, STA, STP, STX, STY, STZ, TAX, TAY, TCD, TCS, TDC, TRB, TSB, TSC, TSX, TXA, TXS, TXY, TYA, TYX, WAI, WDM, XBA, XCE };

pub const Mode = enum {
    imp, // IMPLIED
    acc, // ACCUMULATOR
    imm, // IMMEDIATE
    zpg, // DIRECT
    zpx, // DIRECT,X
    zpy, // DIRECT,Y
    ind, // (DIRECT)
    idx, // (DIRECT,X)
    idy, // (DIRECT),Y
    idl, // [DIRECT]
    idly, // [DIRECT],Y
    abs, // ABSOLUTE
    abx, // ABSOLUTE,X
    aby, // ABSOLUTE,Y
    abl, // LONG
    ablx, // LONG,X
    abi, // (ABSOLUTE)
    abil, // [ABSOLUTE]
    abix, // (ABSOLUTE,X)
    rel, // RELATIVE8
    rell, // RELATIVE16
    stk, // STACK,S
    stky, // (STACK,S),Y
    mov, // SOURCE,DESTINATION
};

pub const Length = struct {
    // base value
    v: u8,
    // -m?
    m: bool,
    // -x?
    x: bool,
};

pub const Opcode = struct {
    instruction: Instruction,
    length: Length,
    mode: Mode,
};

pub const Opcodes: [256]Opcode = [_]Opcode{
    .{ .instruction = .BRK, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .COP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .imm },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .TSB, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ASL, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .PHP, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .ORA, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .ASL, .length = .{ .v = 1, .m = false, .x = false }, .mode = .acc },
    .{ .instruction = .PHD, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .TSB, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ORA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ASL, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ORA, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BPL, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .TRB, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .ASL, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .ORA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .CLC, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .ORA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .INC, .length = .{ .v = 1, .m = false, .x = false }, .mode = .acc },
    .{ .instruction = .TCS, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .TRB, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ORA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .ASL, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .ORA, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .JSR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .JSL, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .BIT, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ROL, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .PLP, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .AND, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .ROL, .length = .{ .v = 1, .m = false, .x = false }, .mode = .acc },
    .{ .instruction = .PLD, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .BIT, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .AND, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ROL, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .AND, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BMI, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .BIT, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .ROL, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .AND, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .SEC, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .AND, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .DEC, .length = .{ .v = 1, .m = false, .x = false }, .mode = .acc },
    .{ .instruction = .TSC, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .BIT, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .AND, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .ROL, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .AND, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .RTI, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .WDM, .length = .{ .v = 2, .m = false, .x = false }, .mode = .imm },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .MVP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .mov },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .LSR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .PHA, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .EOR, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .LSR, .length = .{ .v = 1, .m = false, .x = false }, .mode = .acc },
    .{ .instruction = .PHK, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .JMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .EOR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .LSR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .EOR, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BVC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .MVN, .length = .{ .v = 3, .m = false, .x = false }, .mode = .mov },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .LSR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .EOR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .CLI, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .EOR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .PHY, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .TCD, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .JMP, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .EOR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .LSR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .EOR, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .RTS, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .PER, .length = .{ .v = 3, .m = false, .x = false }, .mode = .imm },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .STZ, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ROR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .PLA, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .ADC, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .ROR, .length = .{ .v = 1, .m = false, .x = false }, .mode = .acc },
    .{ .instruction = .RTL, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .JMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abi },
    .{ .instruction = .ADC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ROR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .ADC, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BVS, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .STZ, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .ROR, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .ADC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .SEI, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .ADC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .PLY, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .TDC, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .JMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abix },
    .{ .instruction = .ADC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .ROR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .ADC, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .BRA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .BRL, .length = .{ .v = 3, .m = false, .x = false }, .mode = .rell },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .STY, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .STX, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .DEY, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .BIT, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .TXA, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .PHB, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .STY, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .STA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .STX, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .STA, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BCC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .STY, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .STX, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpy },
    .{ .instruction = .STA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .TYA, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .STA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .TXS, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .TXY, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .STZ, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .STA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .STZ, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .STA, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .LDY, .length = .{ .v = 3, .m = false, .x = true }, .mode = .imm },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .LDX, .length = .{ .v = 3, .m = false, .x = true }, .mode = .imm },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .LDY, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .LDX, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .TAY, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .LDA, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .TAX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .PLB, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .LDY, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .LDA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .LDX, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .LDA, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BCS, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .LDY, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .LDX, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpy },
    .{ .instruction = .LDA, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .CLV, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .LDA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .TSX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .TYX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .LDY, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .LDA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .LDX, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .LDA, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .CPY, .length = .{ .v = 3, .m = false, .x = true }, .mode = .imm },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .REP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .imm },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .CPY, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .DEC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .INY, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .CMP, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .DEX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .WAI, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .CPY, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .CMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .DEC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .CMP, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BNE, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .PEI, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .DEC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .CMP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .CLD, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .CMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .PHX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .STP, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .JMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abil },
    .{ .instruction = .CMP, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .DEC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .CMP, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
    .{ .instruction = .CPX, .length = .{ .v = 3, .m = false, .x = true }, .mode = .imm },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idx },
    .{ .instruction = .SEP, .length = .{ .v = 2, .m = false, .x = false }, .mode = .imm },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stk },
    .{ .instruction = .CPX, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .INC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpg },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idl },
    .{ .instruction = .INX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .SBC, .length = .{ .v = 3, .m = true, .x = false }, .mode = .imm },
    .{ .instruction = .NOP, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .XBA, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .CPX, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .SBC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .INC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abs },
    .{ .instruction = .SBC, .length = .{ .v = 4, .m = false, .x = false }, .mode = .abl },
    .{ .instruction = .BEQ, .length = .{ .v = 2, .m = false, .x = false }, .mode = .rel },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idy },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .ind },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .stky },
    .{ .instruction = .PEA, .length = .{ .v = 3, .m = false, .x = false }, .mode = .imm },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .INC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .zpx },
    .{ .instruction = .SBC, .length = .{ .v = 2, .m = false, .x = false }, .mode = .idly },
    .{ .instruction = .SED, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .SBC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .aby },
    .{ .instruction = .PLX, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .XCE, .length = .{ .v = 1, .m = false, .x = false }, .mode = .imp },
    .{ .instruction = .JSR, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abix },
    .{ .instruction = .SBC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .INC, .length = .{ .v = 3, .m = false, .x = false }, .mode = .abx },
    .{ .instruction = .SBC, .length = .{ .v = 4, .m = false, .x = false }, .mode = .ablx },
};
